### PR TITLE
updates for Django 2.1

### PR DESCRIPTION
**Pull request by mfwarren**
Did the minimal amount of updates to get this working with the latest Django (2.1.4).

### CODE REVIEW

**Comment by mfwarren** [comment]
signed CLA

**Comment by abhinavpanse** [comment]
Hello @mfwarren this is working great with django 2.1 and python 3. But when I install this app in shopify shop it works, but after that when accessing app through shopify admin panel of shop the app does not work. Please help.      
ss

**Comment by mfwarren** [comment]
@abhinavpanse I got stuck at the same point. I think this repo needs some bigger updates to catch up with newer Shopify APIs.

**Comment by AyyoubOuakkaha** [comment]
Does someone have a working update?  YET ?

**Comment by tanema** [comment]
The app has now been updated to python 3 and django 3

**Pull request closed without merging**
